/**
 * AlphaCounsel - Comprehensive Real Scenario-Based Seed Data
 * Designed for full-spectrum application testing and exhaustive UAT test coverage.
 */

export const SEED_USERS = [
  {
    id: 'usr-1',
    name: 'Marcus Sterling',
    email: 'msterling@alphacounsel.law',
    role: 'MANAGING_PARTNER',
    billingRate: 950,
    barNumber: 'NY-4891024',
    department: 'Commercial Litigation & Governance',
  },
  {
    id: 'usr-2',
    name: 'Eleanor Vance',
    email: 'evance@alphacounsel.law',
    role: 'PARTNER',
    billingRate: 850,
    barNumber: 'CA-294819',
    department: 'Trial Practice & IP Litigation',
  },
  {
    id: 'usr-3',
    name: 'Julian Thorne',
    email: 'jthorne@alphacounsel.law',
    role: 'PARTNER',
    billingRate: 800,
    barNumber: 'NY-5910231',
    department: 'Corporate & M&A',
  },
  {
    id: 'usr-4',
    name: 'Sophia Chen',
    email: 'schen@alphacounsel.law',
    role: 'SENIOR_ASSOCIATE',
    billingRate: 550,
    barNumber: 'CA-348102',
    department: 'Commercial Litigation',
  },
  {
    id: 'usr-5',
    name: 'David Ross',
    email: 'dross@alphacounsel.law',
    role: 'PARALEGAL',
    billingRate: 220,
    department: 'Litigation Support & Discovery',
  },
  {
    id: 'usr-6',
    name: 'Elena Rostova',
    email: 'erostova@alphacounsel.law',
    role: 'BILLING_ADMIN',
    billingRate: 180,
    department: 'Finance & Client Accounting',
  },
  {
    id: 'usr-7',
    name: 'Sarah Jenkins (Apex Dynamics)',
    email: 'sjenkins@apexdynamics.io',
    role: 'CLIENT_PORTAL',
    billingRate: 0,
    department: 'client-1',
  },
  {
    id: 'usr-8',
    name: 'Advocate Vikramaditya Singhania',
    email: 'vsinghania@alphacounsel.law',
    role: 'PARTNER',
    billingRate: 15000,
    barNumber: 'D/1482/2012',
    department: 'Arbitration & Cross-Border Dispute Resolution',
  },
  {
    id: 'usr-9',
    name: 'Neha Sharma',
    email: 'nsharma@alphacounsel.law',
    role: 'ASSOCIATE',
    billingRate: 4500,
    barNumber: 'MAH/5821/2021',
    department: 'Commercial Litigation & Insolvency',
  },
  {
    id: 'usr-10',
    name: 'Dr. Arthur Pendelton (Horizon)',
    email: 'apendelton@horizonbio.com',
    role: 'CLIENT_PORTAL',
    billingRate: 0,
    department: 'client-2',
  },
  {
    id: 'usr-11',
    name: 'Victoria Hastings (Lumina Capital)',
    email: 'vhastings@luminacap.com',
    role: 'CLIENT_PORTAL',
    billingRate: 0,
    department: 'client-3',
  },
  {
    id: 'usr-12',
    name: 'Rajesh Menon (State Bank Creditors)',
    email: 'rmenon@sbi-consortium.in',
    role: 'CLIENT_PORTAL',
    billingRate: 0,
    department: 'client-5',
  },
];

export const SEED_CLIENTS = [
  {
    id: 'client-1',
    name: 'Apex Dynamics Inc.',
    primaryContactName: 'Sarah Jenkins',
    primaryContactEmail: 'sjenkins@apexdynamics.io',
    industry: 'Robotics & Autonomous Systems',
    portalEnabled: true,
  },
  {
    id: 'client-2',
    name: 'Horizon BioSciences Corp.',
    primaryContactName: 'Dr. Arthur Pendelton',
    primaryContactEmail: 'apendelton@horizonbio.com',
    industry: 'Biopharmaceuticals & Oncology',
    portalEnabled: true,
  },
  {
    id: 'client-3',
    name: 'Lumina Capital Partners',
    primaryContactName: 'Victoria Hastings',
    primaryContactEmail: 'vhastings@luminacap.com',
    industry: 'Private Equity & Infrastructure',
    portalEnabled: true,
  },
  {
    id: 'client-4',
    name: 'Sterling Global Logistics',
    primaryContactName: 'Frank Callahan',
    primaryContactEmail: 'fcallahan@sterlinglogistics.com',
    industry: 'Freight & Supply Chain',
    portalEnabled: true,
  },
  {
    id: 'client-5',
    name: 'Consortium of State Bank Creditors',
    primaryContactName: 'Rajesh Menon',
    primaryContactEmail: 'rmenon@sbi-consortium.in',
    industry: 'Banking & Financial Institutions',
    portalEnabled: true,
  },
];

export const SEED_MATTERS = [
  {
    id: 'mat-1',
    matterNumber: 'M-2024-001',
    title: 'Apex Dynamics v. Synapse Robotics',
    clientId: 'client-1',
    clientName: 'Apex Dynamics Inc.',
    status: 'ACTIVE',
    practiceArea: 'Intellectual Property',
    leadPartnerId: 'usr-2', // Eleanor Vance
    assignedUserIds: ['usr-1', 'usr-2', 'usr-4', 'usr-5'],
    courtVenue: 'N.D. Cal. (San Francisco Division)',
    caseDocketNumber: '3:24-cv-01429-VC',
    feeArrangement: 'Hourly Standard',
    budgetCap: 750000,
    evergreenTrustMinimum: 15000,
    hasActiveHold: true,
  },
  {
    id: 'mat-2',
    matterNumber: 'M-2024-002',
    title: 'Synapse Robotics Cross-Claim & Trade Secret Segregation',
    clientId: 'client-1',
    clientName: 'Apex Dynamics Inc.',
    status: 'ACTIVE',
    practiceArea: 'Commercial Litigation',
    leadPartnerId: 'usr-1', // Marcus Sterling
    assignedUserIds: ['usr-1', 'usr-2', 'usr-5'], // usr-4 Sophia Chen is screened out!
    courtVenue: 'Delaware Court of Chancery',
    caseDocketNumber: 'C.A. No. 2024-0312-LWW',
    feeArrangement: 'Hourly Standard',
    budgetCap: 400000,
    evergreenTrustMinimum: 10000,
    hasActiveHold: true,
  },
  {
    id: 'mat-3',
    matterNumber: 'M-2024-003',
    title: 'Horizon BioSciences FTC Antitrust Investigation',
    clientId: 'client-2',
    clientName: 'Horizon BioSciences Corp.',
    status: 'ACTIVE',
    practiceArea: 'Antitrust & Competition',
    leadPartnerId: 'usr-2',
    assignedUserIds: ['usr-2', 'usr-4', 'usr-5'],
    courtVenue: 'Federal Trade Commission / Admin Proceeding',
    caseDocketNumber: 'FTC Matter No. 241-0089',
    feeArrangement: 'Capped Hourly',
    budgetCap: 500000,
    evergreenTrustMinimum: 25000,
    hasActiveHold: false,
  },
  {
    id: 'mat-4',
    matterNumber: 'M-2024-004',
    title: 'Project Titan: Lumina Acquisition of Veridian Energy',
    clientId: 'client-3',
    clientName: 'Lumina Capital Partners',
    status: 'APPROVAL',
    practiceArea: 'Corporate & M&A',
    leadPartnerId: 'usr-3', // Julian Thorne
    assignedUserIds: ['usr-1', 'usr-3', 'usr-4'],
    courtVenue: 'N/A (Private Transaction)',
    feeArrangement: 'Fixed / Flat Fee',
    budgetCap: 250000,
    evergreenTrustMinimum: 20000, // Deficit scenario!
    hasActiveHold: false,
  },
  {
    id: 'mat-5',
    matterNumber: 'M-2024-005',
    title: 'Sterling Logistics v. Bharat Maritime Multimodal Distribution',
    clientId: 'client-4',
    clientName: 'Sterling Global Logistics',
    status: 'ACTIVE',
    practiceArea: 'Commercial Litigation',
    leadPartnerId: 'usr-8', // Vikramaditya Singhania
    assignedUserIds: ['usr-1', 'usr-8', 'usr-9', 'usr-5'],
    courtVenue: 'Mumbai Centre for International Arbitration (MCIA)',
    caseDocketNumber: 'MCIA/ARB/2024/042',
    feeArrangement: 'Capped Hourly',
    budgetCap: 15000000, // ₹1.50 Crore
    evergreenTrustMinimum: 500000, // ₹5.0 Lakhs
    hasActiveHold: false,
  },
  {
    id: 'mat-6',
    matterNumber: 'M-2024-006',
    title: 'Indus FinTech Insolvency & Forensic Asset Tracing',
    clientId: 'client-5',
    clientName: 'Consortium of State Bank Creditors',
    status: 'ACTIVE',
    practiceArea: 'Restructuring',
    leadPartnerId: 'usr-1',
    assignedUserIds: ['usr-1', 'usr-8', 'usr-9', 'usr-5'],
    courtVenue: 'National Company Law Tribunal (NCLT), Principal Bench, New Delhi',
    caseDocketNumber: 'CP (IB) No. 412/PB/2024',
    feeArrangement: 'Hourly Standard',
    budgetCap: 25000000, // ₹2.50 Crore
    evergreenTrustMinimum: 1000000, // ₹10.0 Lakhs
    hasActiveHold: true,
  },
];

export const SEED_ETHICAL_WALLS = [
  {
    id: 'ew-1',
    userId: 'usr-4', // Sophia Chen
    userName: 'Sophia Chen',
    matterId: 'mat-2',
    matterNumber: 'M-2024-002',
    matterTitle: 'Synapse Robotics Cross-Claim & Trade Secret Segregation',
    reason:
      'Prior summer clerkship with adverse party outside counsel (Kirkland & Ellis) on related robotics portfolio. Screened under ABA Model Rule 1.10 & Cal. Rule 1.10 to prevent firm imputation.',
    establishedAt: '2024-03-12T09:00:00Z',
    authorizedBy: 'Marcus Sterling (Managing Partner)',
    active: true,
  },
];

export const SEED_LEGAL_HOLDS = [
  {
    id: 'lh-1',
    matterId: 'mat-1',
    holdTitle: 'Litigation Preservation Notice — Autonomous Vision IP',
    createdAt: '2024-02-05T14:30:00Z',
    createdBy: 'Eleanor Vance',
    status: 'ACTIVE',
    scopeDescription:
      'All source code repositories, engineering commit logs, technical design specs, Slack messages, and executive emails regarding the "Orion-4" lidar guidance system from Jan 2022 to present.',
    custodians: [
      'Dr. Raymond Vance (Chief Architect)',
      'Elena Wu (VP of Engineering)',
      'Sarah Jenkins (General Counsel)',
      'Marcus Brody (Product Lead)',
    ],
    dateRangeStart: '2022-01-01',
    dateRangeEnd: '2024-02-05',
    targets: [
      'GitLab Repository: lidar-guidance-core',
      'Matter Vault Folder: Discovery',
      'Google Workspace Custodian Inboxes',
      'Slack Channels: #proj-orion, #eng-optics',
    ],
    firstApproverId: 'usr-2',
    tamperProofHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'lh-2',
    matterId: 'mat-6',
    holdTitle: 'Litigation Preservation Notice — Forensic Ledgers & Digital Asset Freeze',
    createdAt: '2024-07-05T10:00:00Z',
    createdBy: 'Marcus Sterling',
    status: 'ACTIVE',
    scopeDescription:
      'All core banking transaction switch logs, SAP ERP general ledgers, executive WhatsApp exports, and offshore wire manifests from FY 2021-22 to present.',
    custodians: [
      'Anand Singhal (Promoter / Former MD)',
      'Pooja Kulkarni (Chief Financial Officer)',
      'Rohan Deshmukh (Head of Treasury & Payments)',
      'Rajesh Menon (Resolution Professional Lead)',
    ],
    dateRangeStart: '2021-04-01',
    dateRangeEnd: '2024-07-05',
    targets: [
      'Core Banking Switch Transaction DB',
      'SAP ERP Financial Archives',
      'Matter Vault Folder: Discovery',
      'Promoter Corporate Email & WhatsApp Archives',
    ],
    firstApproverId: 'usr-1',
    tamperProofHash: 'a7c93e4b78912d0981e4fa8367c912048921af789234bde56789123456789012',
  },
];

export const SEED_DOCUMENTS = [
  {
    id: 'doc-1',
    matterId: 'mat-1',
    folder: 'Pleadings',
    title: "Plaintiff's Verified Complaint for Patent Infringement and DTSA Violations",
    fileName: 'Complaint_Apex_v_Synapse_Filed.pdf',
    fileType: 'pdf',
    fileSize: '4.8 MB',
    isHeld: true,
    legalHoldId: 'lh-1',
    tags: ['ECF Filed', 'Complaint', 'Patent', 'Markman'],
  },
  {
    id: 'doc-2',
    matterId: 'mat-1',
    folder: 'Discovery',
    title: 'Certified Deposition Transcript — Nathan Holt (Vol. 1)',
    fileName: 'Deposition_Transcript_Nathan_Holt_Vol1.pdf',
    fileType: 'pdf',
    fileSize: '12.4 MB',
    isHeld: true,
    legalHoldId: 'lh-1',
    tags: ['Deposition', 'Transcript', 'Critical Evidence'],
  },
  {
    id: 'doc-6',
    matterId: 'mat-4',
    folder: 'Contracts',
    title: 'Stock Purchase Agreement — Project Titan Acquisition',
    fileName: 'SPA_Veridian_Lumina_Titan_Execution_Draft.docx',
    fileType: 'docx',
    fileSize: '3.6 MB',
    isHeld: false,
    tags: ['SPA', 'M&A', 'Execution Copy', 'Private Equity'],
  },
  {
    id: 'doc-7',
    matterId: 'mat-5',
    folder: 'Pleadings',
    title: 'Notice of Arbitration & Statement of Claim — Bharat Maritime Multimodal',
    fileName: 'MCIA_Statement_of_Claim_Bharat_Maritime.pdf',
    fileType: 'pdf',
    fileSize: '5.2 MB',
    isHeld: false,
    tags: ['MCIA', 'Arbitration', 'Statement of Claim', 'Maritime Law'],
  },
  {
    id: 'doc-8',
    matterId: 'mat-6',
    folder: 'Discovery',
    title: 'Forensic Audit Report on Indus FinTech Siphoned Accounts',
    fileName: 'EY_Forensic_Investigation_Report_IndusFinTech.pdf',
    fileType: 'pdf',
    fileSize: '24.8 MB',
    isHeld: true,
    legalHoldId: 'lh-2',
    tags: ['Forensic Audit', 'Section 66 IBC', 'NCLT Evidence', 'Fund Diversion'],
  },
];

export const SEED_TIME_ENTRIES = [
  {
    id: 'time-1',
    matterId: 'mat-1',
    userId: 'usr-2',
    hours: 3.5,
    rate: 850,
    total: 2975,
    status: 'PARTNER_APPROVED',
  },
  {
    id: 'time-2',
    matterId: 'mat-1',
    userId: 'usr-4',
    hours: 5.2,
    rate: 550,
    total: 2860,
    status: 'WIP',
  },
  {
    id: 'time-8',
    matterId: 'mat-4',
    userId: 'usr-3',
    hours: 10.0,
    rate: 800,
    total: 8000,
    status: 'WIP',
  },
  {
    id: 'time-9',
    matterId: 'mat-5',
    userId: 'usr-8',
    hours: 15.0,
    rate: 15000,
    total: 225000,
    status: 'PARTNER_APPROVED',
  },
  {
    id: 'time-10',
    matterId: 'mat-5',
    userId: 'usr-9',
    hours: 20.0,
    rate: 4500,
    total: 90000,
    status: 'WIP',
  },
  {
    id: 'time-11',
    matterId: 'mat-6',
    userId: 'usr-1',
    hours: 8.0,
    rate: 950,
    total: 7600,
    status: 'PARTNER_APPROVED',
  },
];

export const SEED_EXPENSES = [
  {
    id: 'exp-1',
    matterId: 'mat-1',
    userId: 'usr-5',
    amount: 12500,
    billable: true,
    status: 'UNBILLED',
  },
  {
    id: 'exp-4',
    matterId: 'mat-5',
    userId: 'usr-9',
    amount: 150000,
    billable: true,
    status: 'UNBILLED',
  },
  {
    id: 'exp-5',
    matterId: 'mat-6',
    userId: 'usr-5',
    amount: 450000,
    billable: true,
    status: 'UNBILLED',
  },
];

export const SEED_INVOICES = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2024-0842',
    matterId: 'mat-1',
    clientId: 'client-1',
    totalAmount: 9902,
    amountPaid: 9902,
    balanceDue: 0,
    status: 'PAID',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2024-0915',
    matterId: 'mat-1',
    clientId: 'client-1',
    totalAmount: 22955,
    amountPaid: 10000,
    balanceDue: 12955,
    status: 'PART_PAID',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2024-1001',
    matterId: 'mat-5',
    clientId: 'client-4',
    totalAmount: 2500000,
    amountPaid: 2500000,
    balanceDue: 0,
    status: 'PAID',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2024-1002',
    matterId: 'mat-5',
    clientId: 'client-4',
    totalAmount: 1500000,
    amountPaid: 0,
    balanceDue: 1500000,
    status: 'ISSUED',
  },
  {
    id: 'inv-105',
    invoiceNumber: 'INV-2024-1003',
    matterId: 'mat-4',
    clientId: 'client-3',
    totalAmount: 15000,
    amountPaid: 0,
    balanceDue: 15000,
    status: 'ISSUED',
  },
];

export const SEED_PAYMENTS = [
  {
    id: 'pay-1',
    invoiceId: 'inv-101',
    matterId: 'mat-1',
    amount: 9902,
    method: 'Trust Transfer',
  },
  {
    id: 'pay-2',
    invoiceId: 'inv-102',
    matterId: 'mat-1',
    amount: 10000,
    method: 'Wire',
  },
  {
    id: 'pay-3',
    invoiceId: 'inv-103',
    matterId: 'mat-5',
    amount: 2500000,
    method: 'Wire',
  },
];

export const SEED_TRUST_TRANSACTIONS = [
  {
    id: 'tr-1',
    matterId: 'mat-1',
    type: 'RETAINER_DEPOSIT',
    amount: 50000,
  },
  {
    id: 'tr-2',
    matterId: 'mat-1',
    type: 'TRUST_APPLIED_TO_INVOICE',
    amount: -9902,
  },
  {
    id: 'tr-3',
    matterId: 'mat-3',
    type: 'RETAINER_DEPOSIT',
    amount: 35000,
  },
  {
    id: 'tr-4',
    matterId: 'mat-4',
    type: 'RETAINER_DEPOSIT',
    amount: 5000, // Evergreen min ₹20k -> Deficit ₹15k
  },
  {
    id: 'tr-5',
    matterId: 'mat-5',
    type: 'RETAINER_DEPOSIT',
    amount: 1000000, // ₹10.0 Lakhs
  },
  {
    id: 'tr-6',
    matterId: 'mat-6',
    type: 'RETAINER_DEPOSIT',
    amount: 7500000, // ₹75.0 Lakhs
  },
];
